services:
    astrotuxlauncher:
        tty: true
        stdin_open: true
        container_name: astrotuxlauncher
        build:
            context: .
            dockerfile: Dockerfile
            target: astrotuxlauncher
        image: mekumiao/astrotuxlauncher
        ports:
            - 7777:7777/udp
        volumes:
            - ./AstroneerServer:/astrotuxlauncher/AstroneerServer
            - ./libs:/astrotuxlauncher/libs
